DROP DATABASE IF EXISTS DBCARTAOCREDITO;
CREATE DATABASE DBCARTAOCREDITO;
USE DBCARTAOCREDITO;

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	CPF CHAR(11) NOT NULL,
	RG VARCHAR(16),
	LOGRADOURO VARCHAR(100),
	NUMERO VARCHAR(10),
	BAIRRO VARCHAR(100),
	CIDADE VARCHAR(100),
	UF CHAR(2),
	COMPLEMENTO VARCHAR(100),
	DT_NASCIMENTO DATE,
	TELEFONE_RESIDENCIAL VARCHAR(15),
	TELEFONE_COMERCIAL VARCHAR(15),
	TELEFONE_RECADO VARCHAR(15)
);

CREATE TABLE CARTAO (
	IDCARTAO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDCLIENTE INT NOT NULL,
	NUMERO CHAR(17) NOT NULL,
	DIA_VENCIMENTO INT NOT NULL,
	LIMITE NUMERIC(8,2),
	CONSTRAINT FK_CARTAO_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE DEBITO (
	IDDEBITO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDCARTAO INT NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	PARCELA INT,
	VALOR NUMERIC(8,2) NOT NULL, 
	DT_DEBITO DATETIME,
	CONSTRAINT FK_DEBITO_CARTAO FOREIGN KEY (IDCARTAO) REFERENCES CARTAO(IDCARTAO)
);

CREATE TABLE BOLETO (
	IDBOLETO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDCARTAO INT NOT NULL,
	DT_GERACAO DATE NOT NULL,
	DT_VENCIMENTO DATE NOT NULL,
	VALOR_TOTAL NUMERIC(8,2) NOT NULL, 
	DT_PAGAMENTO DATE,
	VALOR_PAGO NUMERIC(8,2), 
	CONSTRAINT FK_BOLETO_CLIENTE FOREIGN KEY (IDCARTAO) REFERENCES CARTAO(IDCARTAO)
);


CREATE TABLE ITEM_BOLETO (
	IDITEM_BOLETO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDBOLETO INT NOT NULL,
	IDDEBITO INT NOT NULL,
	CONSTRAINT FK_ITEM_BOLETO_BOLETO FOREIGN KEY (IDBOLETO) REFERENCES BOLETO(IDBOLETO),
	CONSTRAINT FK_ITEM_BOLETO_DEBITO FOREIGN KEY (IDDEBITO) REFERENCES DEBITO(IDDEBITO)
);
-- 1
CREATE USER 'ADRIANA'@'%' IDENTIFIED BY '123';  
GRANT SELECT, UPDATE ON DBCARTAOCREDITO.CARTAO TO 'ADRIANA'@'%';

-- 2
CREATE USER 'ALFREDO'@'%' IDENTIFIED BY 'COMERCIAL';  
GRANT SELECT ON DBCARTAOCREDITO TO 'ALFREDO'@'%';

-- 3
CREATE USER 'ANA'@'%' IDENTIFIED BY 'DIREÇÃO';  
GRANT SELECT, INSERT, UPDATE ON DBCARTAOCREDITO TO 'ANA'@'%';
GRANT SELECT, INSERT, UPDATE ON DBCARTAOCREDITO.CLIENTE TO 'ANA'@'%';

-- 4
CREATE USER 'ANDERSON'@'%' IDENTIFIED BY 'COMERCIAL';  
GRANT SELECT ON DBCARTAOCREDITO.CARTAO TO 'ANDERSON'@'%';

-- 5
CREATE USER 'BRUNA'@'%' IDENTIFIED BY 'SAC';  
GRANT SELECT, UPDATE ON DBCARTAOCREDITO.CLIENTE TO 'BRUNA'@'%';
GRANT SELECT ON DBCARTAOCREDITO.BOLETO TO 'BRUNA'@'%';

-- 6
CREATE USER 'CARLA'@'%' IDENTIFIED BY 'FATURAMENTO';  
GRANT SELECT, INSERT, UPDATE, DELETE ON DBCARTAOCREDITO.CARTAO TO 'CARLA'@'%';
GRANT SELECT ON DBCARTAOCREDITO TO 'CARLA'@'%';

-- 7
CREATE USER 'CARLOS'@'%' IDENTIFIED BY 'GERENCIA';  
GRANT SELECT, INSERT, UPDATE, DELETE ON DBCARTAOCREDITO TO 'CARLOS'@'%';

-- 8
CREATE USER 'CLEBER'@'%' IDENTIFIED BY 'PROJETO TI';  
GRANT SELECT ON DBCARTAOCREDITO TO 'CLEBER'@'%';

-- 9
CREATE USER 'DANIELE'@'%' IDENTIFIED BY 'CONTABILIDADE';  
GRANT SELECT, UPDATE ON DBCARTAOCREDITO.BOLETO TO 'DANIELE'@'%';
GRANT SELECT ON DBCARTAOCREDITO TO 'DANIELE'@'%';
GRANT SELECT, UPDATE ON DBCARTAOCREDITO.CARTAO TO 'DANIELE'@'%';

-- 10
CREATE USER 'GEOVANA'@'%' IDENTIFIED BY 'FATURAMENTO';  
GRANT SELECT, UPDATE, INSERT, DELETE ON DBCARTAOCREDITO.CARTAO TO 'GEOVANA'@'%';
GRANT SELECT, UPDATE, INSERT, DELETE ON DBCARTAOCREDITO.BOLETO TO 'GEOVANA'@'%';
GRANT SELECT, UPDATE, INSERT, DELETE ON DBCARTAOCREDITO.DEBITO TO 'GEOVANA'@'%';
GRANT SELECT, UPDATE, INSERT, DELETE ON DBCARTAOCREDITO.ITEM_BOLETO TO 'GEOVANA'@'%';

-- 11
CREATE USER 'GISELE'@'%' IDENTIFIED BY 'COMERCIAL';  
GRANT SELECT, UPDATE, INSERT ON DBCARTAOCREDITO.CLIENTE TO 'GISELE'@'%';

-- 12
CREATE USER 'GRAZIELE'@'%' IDENTIFIED BY 'COMERCIAL';  
GRANT SELECT, UPDATE, INSERT ON DBCARTAOCREDITO.CLIENTE TO 'GRAZIELE'@'%';

-- 13
CREATE USER 'JULIANO'@'%' IDENTIFIED BY 'SAC';  
GRANT SELECT, UPDATE ON DBCARTAOCREDITO.CLIENTE TO 'JULIANO'@'%';

-- 14
CREATE USER 'MARCOS'@'%' IDENTIFIED BY 'FINANCEIRO';  
GRANT SELECT, UPDATE, INSERT, DELETE ON DBCARTAOCREDITO.CARTAO TO 'MARCOS'@'%';
GRANT SELECT ON DBCARTAOCREDITO TO 'MARCOS'@'%';
GRANT SELECT, UPDATE, INSERT, DELETE ON DBCARTAOCREDITO.CLIENTE TO 'MARCOS'@'%';

-- 15
CREATE USER 'MICHELLY'@'%' IDENTIFIED BY 'RH';  
GRANT SELECT ON DBCARTAOCREDITO.BOLETO TO 'MICHELLY'@'%';

-- 16
CREATE USER 'RAFELA'@'%' IDENTIFIED BY 'FATURAMENTO';  
GRANT SELECT, UPDATE, INSERT, DELETE ON DBCARTAOCREDITO.CARTAO TO 'RAFAELA'@'%';
GRANT SELECT, UPDATE, INSERT, DELETE ON DBCARTAOCREDITO.BOLETO TO 'RAFAELA'@'%';
GRANT SELECT, UPDATE, INSERT, DELETE ON DBCARTAOCREDITO.DEBITO TO 'RAFAELA'@'%';
GRANT SELECT, UPDATE, INSERT, DELETE ON DBCARTAOCREDITO.ITEM_BOLETO TO 'RAFAELA'@'%';

-- 17
CREATE USER 'VILMAR'@'%' IDENTIFIED BY 'COMERCIAL';  
GRANT SELECT, UPDATE, INSERT, DELETE ON DBCARTAOCREDITO.CLIENTE TO 'VILMAR'@'%';