SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBCLASSIFICACAO;
CREATE DATABASE DBCLASSIFICACAO;
USE DBCLASSIFICACAO;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(45)
	, IDADE INT
);

CREATE TABLE CLASSIFICACAO (	
	CRIANCAS INT
	, JOVENS INT
	, ADULTOS INT
);

INSERT INTO CLASSIFICACAO VALUES (0,0,0);

/*
Regra:
abaixo 10 - Criancas
10 a 18 - Jovens
Acima de 18 - Adulto
*/

INSERT INTO aluno VALUES (1,'Marcus' , 20);
INSERT INTO aluno VALUES (1,'Milena' , 15);
INSERT INTO aluno VALUES (1,'Pocahontas' , 7);

DELIMITER $$
CREATE TRIGGER tr_classificacao_ai AFTER INSERT ON aluno FOR EACH ROW
BEGIN

	IF NEW.idade < 10 THEN
		UPDATE classificacao SET criancas = criancas +1;   
	ELSEIF NEW.idade > 10 AND  NEW.idade < 18 THEN
		UPDATE classificacao SET jovens = jovens + 1;
	ELSE 
		UPDATE classificacao SET adulto = adulto + 1;
	END IF;

END $$